### PR TITLE
Fix translation error.

### PR DESCRIPTION
**Pull request by appleway**
There is no weight in the original statement.

### CODE REVIEW

**Comment by MnO2** [comment]
@appleway  Could you do me a favor to fix the same error in simplified chinese version. It's located at zh-cn/ch08.

**Comment by appleway** [comment]
Done for simplified Chinese version.

**Comment by MnO2** [comment]
@appleway Thanks for the help, but could you merge the two commits into one?

**Comment by appleway** [comment]
Sorry, I don't have pc w/ me. If you wanna merge them into a single commit, you can just ignore this PR and then make another commit w/ both fixes by yourself since this is a super easy fix.

**Comment by MnO2** [comment]
OK, no problem.

**Pull request closed without merging**
